name: Generate Snake

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake (light mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ravi5781
          outputs: dist/snake.svg

      - name: Generate Snake (dark mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ravi5781
          outputs: dist/snake-dark.svg
          snake_color: "#00FF00"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
